version: '3'
services:
 db:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: siva
    MYSQL_DATABASE: testdb
    MYSQL_USER: testuser
    MYSQL_PASSWORD: root
  ports:
   - 3306:3306
  volumes:
   - ./db:/docker-entrypoint-initdb.d   
  
 web:
  depends_on:
   - db       
  image: tomcat:8.0-alpine
 
  ports:
   - 8989:8080
  volumes:
   - ./db:/docker-entrypoint-initdb.d   
  
  
